In [1]:
#numpy - numerical python, numeric operation

In [2]:
import numpy as np

In [4]:
l1=[10,20,30,40]
n1=np.array(l1)

In [5]:
n1

array([10, 20, 30, 40])

In [6]:
type(n1)

numpy.ndarray

In [8]:
l2=[1,2,3,4,5]
n2=np.array([l1,l2])

In [9]:
n2

array([list([10, 20, 30, 40]), list([1, 2, 3, 4, 5])], dtype=object)

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [16]:
np4=np.random.randint(2,20,3)
print(np4)
np4[0]

[18 13  7]


18

In [21]:
n2.shape

(2,)

In [22]:
n3=np.array([[1,2,3],[4,5,6]])

In [23]:
n3.shape

(2, 3)

In [24]:
n3.shape = (3,2)

In [25]:
n3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
n4 = np.array([1,2,3,4])

In [31]:
nstack1=np.vstack((n1,n4))

In [32]:
nstack1

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [33]:
hstack1=np.hstack((n1,n4))

In [34]:
hstack1

array([10, 20, 30, 40,  1,  2,  3,  4])

In [35]:
col_stack=np.column_stack((n1,n4))

In [36]:

col_stack

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [37]:
import numpy as np

In [38]:
n1=np.array([1,2,3,4,5])
n2=np.array([1,2,6,7,8])


In [40]:
np.intersect1d(n1,n2)

array([1, 2])

In [41]:
np.setdiff1d(n1,n2)

array([3, 4, 5])

In [42]:
np.setdiff1d(n2,n1)

array([6, 7, 8])

In [43]:
np.sum([n1,n2])

39

In [45]:
np.sum([n1,n2],axis=1)

array([15, 24])

In [46]:
n1

array([1, 2, 3, 4, 5])

In [47]:
n2

array([1, 2, 6, 7, 8])

In [48]:
np.sum([n1,n2],axis=0)

array([ 2,  4,  9, 11, 13])

In [49]:
n1+1

array([2, 3, 4, 5, 6])

In [50]:
n2-2

array([-1,  0,  4,  5,  6])

In [51]:
n2/2

array([0.5, 1. , 3. , 3.5, 4. ])

In [56]:
n5=np.random.randint(1,100,5)
n5

array([62, 75, 19, 87, 40])

In [57]:
n5.mean()

56.6

In [58]:
n5.max()

87

In [59]:
n5.min()

19

In [60]:
n6=np.array([10,20,30,40,50])

In [61]:
np.save("n6_array",n6)

In [62]:
n6_new=np.load("n6_array.npy")

In [63]:
n6_new

array([10, 20, 30, 40, 50])